### ISSUE TITLE
Wrong leader

### ISSUE THREAD

**Issue by PanzerErwin** [stuffi3000/Cold-War--The-Iron-Curtain#6]
Might have already been noticed, and it is dev version, but instead of Nikita Khrushchev, there is Nikita Krushev.
![hoi4_8](https://user-images.githubusercontent.com/17228632/34965992-3be6fa9c-fa0d-11e7-8b54-f08efbbaaa88.png)

**Comment by PanzerErwin** [comment]
In 1960 Scenario.

**Comment by stuffi3000** [comment]
It's not the correct leader. Apparently somebody messed with the history files again. I'll fix it as soon as I can
